### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#22]

**Comment by Falconiac** [comment]
## User Story

As a User
I want to have a Navbar
so that I can navigate easy in the app 

## AC

- [x] Navbar should be reachable on every page

- [ ] should have navigationlinks for all pages

- [ ] should have a button to logout

## Task

- [ ] create new branch
- [ ] create a navbar component


## Complexity

m
