### ISSUE TITLE
BE - MongoDB

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#3]
## User Story

As a User
I want to have a database
so that I can persist my data

## AC

- [ ] Input data should be persisted in database

- [ ] Data should be retrievable

- [ ] Data should be stored

## Task

- [ ] create new branch
- [ ] Create a MongoDB

---

create a MongoDB with two Collections:

- [ ] user 
- [ ] evaluation

---

 connect MongoDB to backend:

- [ ] Implement URI in backend: Application propertys

---

- [ ] Create Model "User" in backend with annotaion: 
- [ ] @ Builder
- [ ] @ Data
- [ ] @ AllArgsConstructor
- [ ] @ NoArgsConstructor
- [ ] @ Document(collection = "user")

---

- [ ] Create Model "Evaluation" in backend with annotaion: 
- [ ] @ Builder
- [ ] @ Data
- [ ] @ AllArgsConstructor
- [ ] @ NoArgsConstructor
- [ ] @ Document(collection = "evaluation")

--- 

- [ ] Create two repository in backend:
- [ ] Both with annotation: @Repository
- [ ]  UserRepo: public interface UserRepo extends MongoRepository<User, String>{}
- [ ] EvaluationRepo: public interface UserRepo extends MongoRepository<Evaluation, String>{}

## Complexity

L
