### ISSUE TITLE
FE - Register-Component

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#4]
## User Story

As a User
I want to register
so that I have a own, private account for my data

## AC

- [ ] The user should be able to create a own account

- [ ] The user must insert all his data, every field is required

## Design

![Image](https://user-images.githubusercontent.com/103875201/196703426-40546fb8-9a9a-4818-91a1-2c2a3213e6e9.png)

![Image](https://user-images.githubusercontent.com/103875201/196703476-f3996945-f8e6-4609-9ba5-bb61bb4d0d04.png)

![Image](https://user-images.githubusercontent.com/103875201/196703495-79df86f6-5f4c-4541-aa14-02fdbecfb646.png)

![Image](https://user-images.githubusercontent.com/103875201/196703525-2b3f8b08-3165-4cf0-8c85-3d2cb34cd5ac.png)

![Image](https://user-images.githubusercontent.com/103875201/196703554-26593c3f-0d81-4629-ba39-81f6973a6cc3.png)

## Task

- [ ] create new branch
- [ ] create a page named register
- [ ] create button with route to "/lregister" on home-screen
- [ ] create form component
- [ ] writing tests

## Complexity

L
