### ISSUE TITLE
BE - Register-Component

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#5]
## User Story

As a User
I want to register
so that I have a own, private account for my data

## AC

- [ ] All entered data should be transferred from the frontend to the backend and stored in the database

## Task

- [ ] create new branch
- [ ] create a user controller with post mapping
- [ ] create a id-service
- [ ] create a user service with a addNewUser-method
- [ ] create a userDTO
- [ ] writing tests

## Complexity

M
