### ISSUE TITLE
FE - Login-Component

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#6]
## User Story

As a User
I want to login
so that I can edit my assessments within my account

## AC

- [ ] The user should be able to login

- [ ] After successfully login the user gets automatic navigated to user area

## Design

![Image](https://user-images.githubusercontent.com/103875201/196981400-6d589b88-833b-416d-9f42-ed41e814695a.png)

## Task

- [ ] create new branch
- [ ] create login field on home-screen
- [ ] create a page named userArea
- [ ] create button with route to "/userArea" on home-screen
- [ ] writing tests

## Complexity

M
