### ISSUE TITLE
BE - ID-Service

### ISSUE THREAD

**Issue by Falconiac** [Falconiac/gefahrometer-capstone#8]
## Developer Story

As a developer
I want to have a id-service
so that every data has his own automaticly generated id

## AC

- [ ] Every new data, wich incomes should become a own unique id

## Task

- [ ] create new branch
- [ ] create a UserDTO
- [ ] create a id-service 
- [ ] writing tests

## Complexity

 S
